//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TicketMasterModel", "FK_Bookings_PaymentStatus", "PaymentStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BrokerTicketingExample.Models.PaymentStatu), "Bookings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BrokerTicketingExample.Models.Booking), true)]
[assembly: EdmRelationshipAttribute("TicketMasterModel", "FK_Bookings_PrintStatus", "PrintStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BrokerTicketingExample.Models.PrintStatu), "Bookings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BrokerTicketingExample.Models.Booking), true)]

#endregion

namespace BrokerTicketingExample.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TicketMasterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TicketMasterEntities object using the connection string found in the 'TicketMasterEntities' section of the application configuration file.
        /// </summary>
        public TicketMasterEntities() : base("name=TicketMasterEntities", "TicketMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TicketMasterEntities object.
        /// </summary>
        public TicketMasterEntities(string connectionString) : base(connectionString, "TicketMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TicketMasterEntities object.
        /// </summary>
        public TicketMasterEntities(EntityConnection connection) : base(connection, "TicketMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Booking> Bookings
        {
            get
            {
                if ((_Bookings == null))
                {
                    _Bookings = base.CreateObjectSet<Booking>("Bookings");
                }
                return _Bookings;
            }
        }
        private ObjectSet<Booking> _Bookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaymentStatu> PaymentStatus
        {
            get
            {
                if ((_PaymentStatus == null))
                {
                    _PaymentStatus = base.CreateObjectSet<PaymentStatu>("PaymentStatus");
                }
                return _PaymentStatus;
            }
        }
        private ObjectSet<PaymentStatu> _PaymentStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrintStatu> PrintStatus
        {
            get
            {
                if ((_PrintStatus == null))
                {
                    _PrintStatus = base.CreateObjectSet<PrintStatu>("PrintStatus");
                }
                return _PrintStatus;
            }
        }
        private ObjectSet<PrintStatu> _PrintStatus;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookings(Booking booking)
        {
            base.AddObject("Bookings", booking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaymentStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaymentStatus(PaymentStatu paymentStatu)
        {
            base.AddObject("PaymentStatus", paymentStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrintStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrintStatus(PrintStatu printStatu)
        {
            base.AddObject("PrintStatus", printStatu);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> BrokerPaymentMessageProcessed()
        {
            return base.ExecuteFunction<global::System.String>("BrokerPaymentMessageProcessed");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> BrokerPrintMessageProcessed()
        {
            return base.ExecuteFunction<global::System.String>("BrokerPrintMessageProcessed");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="eventId">No Metadata Documentation available.</param>
        /// <param name="quantity">No Metadata Documentation available.</param>
        /// <param name="creditCard">No Metadata Documentation available.</param>
        public int CreateBooking(Nullable<global::System.Int32> eventId, Nullable<global::System.Int32> quantity, global::System.String creditCard)
        {
            ObjectParameter eventIdParameter;
            if (eventId.HasValue)
            {
                eventIdParameter = new ObjectParameter("EventId", eventId);
            }
            else
            {
                eventIdParameter = new ObjectParameter("EventId", typeof(global::System.Int32));
            }
    
            ObjectParameter quantityParameter;
            if (quantity.HasValue)
            {
                quantityParameter = new ObjectParameter("Quantity", quantity);
            }
            else
            {
                quantityParameter = new ObjectParameter("Quantity", typeof(global::System.Int32));
            }
    
            ObjectParameter creditCardParameter;
            if (creditCard != null)
            {
                creditCardParameter = new ObjectParameter("CreditCard", creditCard);
            }
            else
            {
                creditCardParameter = new ObjectParameter("CreditCard", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("CreateBooking", eventIdParameter, quantityParameter, creditCardParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetEvents_Result> GetEvents()
        {
            return base.ExecuteFunction<GetEvents_Result>("GetEvents");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketMasterModel", Name="Booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Booking object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        /// <param name="creditCard">Initial value of the CreditCard property.</param>
        /// <param name="billAmount">Initial value of the BillAmount property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="cancelled">Initial value of the Cancelled property.</param>
        /// <param name="paymentStatus">Initial value of the PaymentStatus property.</param>
        /// <param name="printStatus">Initial value of the PrintStatus property.</param>
        public static Booking CreateBooking(global::System.Int32 id, global::System.Int32 eventId, global::System.String creditCard, global::System.Decimal billAmount, global::System.Int32 quantity, global::System.Boolean cancelled, global::System.Int32 paymentStatus, global::System.Int32 printStatus)
        {
            Booking booking = new Booking();
            booking.Id = id;
            booking.EventId = eventId;
            booking.CreditCard = creditCard;
            booking.BillAmount = billAmount;
            booking.Quantity = quantity;
            booking.Cancelled = cancelled;
            booking.PaymentStatus = paymentStatus;
            booking.PrintStatus = printStatus;
            return booking;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value, "EventId");
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreditCard
        {
            get
            {
                return _CreditCard;
            }
            set
            {
                OnCreditCardChanging(value);
                ReportPropertyChanging("CreditCard");
                _CreditCard = StructuralObject.SetValidValue(value, false, "CreditCard");
                ReportPropertyChanged("CreditCard");
                OnCreditCardChanged();
            }
        }
        private global::System.String _CreditCard;
        partial void OnCreditCardChanging(global::System.String value);
        partial void OnCreditCardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BillAmount
        {
            get
            {
                return _BillAmount;
            }
            set
            {
                OnBillAmountChanging(value);
                ReportPropertyChanging("BillAmount");
                _BillAmount = StructuralObject.SetValidValue(value, "BillAmount");
                ReportPropertyChanged("BillAmount");
                OnBillAmountChanged();
            }
        }
        private global::System.Decimal _BillAmount;
        partial void OnBillAmountChanging(global::System.Decimal value);
        partial void OnBillAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, "Quantity");
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Cancelled
        {
            get
            {
                return _Cancelled;
            }
            set
            {
                OnCancelledChanging(value);
                ReportPropertyChanging("Cancelled");
                _Cancelled = StructuralObject.SetValidValue(value, "Cancelled");
                ReportPropertyChanged("Cancelled");
                OnCancelledChanged();
            }
        }
        private global::System.Boolean _Cancelled;
        partial void OnCancelledChanging(global::System.Boolean value);
        partial void OnCancelledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaymentStatus
        {
            get
            {
                return _PaymentStatus;
            }
            set
            {
                OnPaymentStatusChanging(value);
                ReportPropertyChanging("PaymentStatus");
                _PaymentStatus = StructuralObject.SetValidValue(value, "PaymentStatus");
                ReportPropertyChanged("PaymentStatus");
                OnPaymentStatusChanged();
            }
        }
        private global::System.Int32 _PaymentStatus;
        partial void OnPaymentStatusChanging(global::System.Int32 value);
        partial void OnPaymentStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrintStatus
        {
            get
            {
                return _PrintStatus;
            }
            set
            {
                OnPrintStatusChanging(value);
                ReportPropertyChanging("PrintStatus");
                _PrintStatus = StructuralObject.SetValidValue(value, "PrintStatus");
                ReportPropertyChanged("PrintStatus");
                OnPrintStatusChanged();
            }
        }
        private global::System.Int32 _PrintStatus;
        partial void OnPrintStatusChanging(global::System.Int32 value);
        partial void OnPrintStatusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketMasterModel", "FK_Bookings_PaymentStatus", "PaymentStatus")]
        public PaymentStatu PaymentStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PaymentStatu>("TicketMasterModel.FK_Bookings_PaymentStatus", "PaymentStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PaymentStatu>("TicketMasterModel.FK_Bookings_PaymentStatus", "PaymentStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PaymentStatu> PaymentStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PaymentStatu>("TicketMasterModel.FK_Bookings_PaymentStatus", "PaymentStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PaymentStatu>("TicketMasterModel.FK_Bookings_PaymentStatus", "PaymentStatus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketMasterModel", "FK_Bookings_PrintStatus", "PrintStatus")]
        public PrintStatu PrintStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrintStatu>("TicketMasterModel.FK_Bookings_PrintStatus", "PrintStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrintStatu>("TicketMasterModel.FK_Bookings_PrintStatus", "PrintStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrintStatu> PrintStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrintStatu>("TicketMasterModel.FK_Bookings_PrintStatus", "PrintStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrintStatu>("TicketMasterModel.FK_Bookings_PrintStatus", "PrintStatus", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketMasterModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="totalTicketCount">Initial value of the TotalTicketCount property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static Event CreateEvent(global::System.Int32 id, global::System.String name, global::System.DateTime date, global::System.Int32 totalTicketCount, global::System.Decimal price)
        {
            Event @event = new Event();
            @event.Id = id;
            @event.Name = name;
            @event.Date = date;
            @event.TotalTicketCount = totalTicketCount;
            @event.Price = price;
            return @event;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalTicketCount
        {
            get
            {
                return _TotalTicketCount;
            }
            set
            {
                OnTotalTicketCountChanging(value);
                ReportPropertyChanging("TotalTicketCount");
                _TotalTicketCount = StructuralObject.SetValidValue(value, "TotalTicketCount");
                ReportPropertyChanged("TotalTicketCount");
                OnTotalTicketCountChanged();
            }
        }
        private global::System.Int32 _TotalTicketCount;
        partial void OnTotalTicketCountChanging(global::System.Int32 value);
        partial void OnTotalTicketCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketMasterModel", Name="PaymentStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaymentStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaymentStatu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static PaymentStatu CreatePaymentStatu(global::System.Int32 id, global::System.String status)
        {
            PaymentStatu paymentStatu = new PaymentStatu();
            paymentStatu.Id = id;
            paymentStatu.Status = status;
            return paymentStatu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketMasterModel", "FK_Bookings_PaymentStatus", "Bookings")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("TicketMasterModel.FK_Bookings_PaymentStatus", "Bookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("TicketMasterModel.FK_Bookings_PaymentStatus", "Bookings", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketMasterModel", Name="PrintStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrintStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrintStatu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static PrintStatu CreatePrintStatu(global::System.Int32 id, global::System.String status)
        {
            PrintStatu printStatu = new PrintStatu();
            printStatu.Id = id;
            printStatu.Status = status;
            return printStatu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketMasterModel", "FK_Bookings_PrintStatus", "Bookings")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("TicketMasterModel.FK_Bookings_PrintStatus", "Bookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("TicketMasterModel.FK_Bookings_PrintStatus", "Bookings", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TicketMasterModel", Name="GetEvents_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetEvents_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetEvents_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="totalTicketCount">Initial value of the TotalTicketCount property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static GetEvents_Result CreateGetEvents_Result(global::System.Int32 id, global::System.String name, global::System.DateTime date, global::System.Int32 totalTicketCount, global::System.Decimal price)
        {
            GetEvents_Result getEvents_Result = new GetEvents_Result();
            getEvents_Result.Id = id;
            getEvents_Result.Name = name;
            getEvents_Result.Date = date;
            getEvents_Result.TotalTicketCount = totalTicketCount;
            getEvents_Result.Price = price;
            return getEvents_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, "Id");
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalTicketCount
        {
            get
            {
                return _TotalTicketCount;
            }
            set
            {
                OnTotalTicketCountChanging(value);
                ReportPropertyChanging("TotalTicketCount");
                _TotalTicketCount = StructuralObject.SetValidValue(value, "TotalTicketCount");
                ReportPropertyChanged("TotalTicketCount");
                OnTotalTicketCountChanged();
            }
        }
        private global::System.Int32 _TotalTicketCount;
        partial void OnTotalTicketCountChanging(global::System.Int32 value);
        partial void OnTotalTicketCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Remaining
        {
            get
            {
                return _Remaining;
            }
            set
            {
                OnRemainingChanging(value);
                ReportPropertyChanging("Remaining");
                _Remaining = StructuralObject.SetValidValue(value, "Remaining");
                ReportPropertyChanged("Remaining");
                OnRemainingChanged();
            }
        }
        private Nullable<global::System.Int32> _Remaining;
        partial void OnRemainingChanging(Nullable<global::System.Int32> value);
        partial void OnRemainingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    }

    #endregion

}
